day20/catsapps/urls.py
from django.urls import path

from . import views

app_name = "catsapps"

urlpatterns = [
    # HomePage
    path("", views.index, name="index"),
    path("kind/", views.kind, name="kinds"),
    #path("kindbycats/<int:kind_id>", views.kindbycats, name="kind"),
    path("behavor/", views.behavor, name="behavors"),
    #path("behavorbycats/<int:behavor_id>", views.behavorbycats, name="behavor"),
    path("color/", views.color, name="colors"),
    #path("colorbycats/<int:color_id>", views.colorbycats, name="color"),
    path("cats/", views.cats, name="cats"),
    path("addCats/", views.add_cats, name="addCats"),
    path("update_cat/<int:cat_id>", views.update_cats, name="UpdateCat"),
]
# "name/"- просто ссылка, views должен совпадать с нашей созданной функцией в ней, name="names"- как мы будем обращаться по ссылке в html

day20/first_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("first/", include("firstapps.urls")),
    path("fin/", include("finapp.urls")),
    path("", include("catsapps.urls")),
    path("users/", include("users.urls")),
]

day20/users/urls.py
from django.urls import path, include

from . import views

app_name = "users"


urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register/", views.register, name="register"),
]

day20/catsapps/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Color(models.Model):
    color = models.CharField(max_length=15)

    def __str__(self) -> str:
        return f"{self.color}"


class Behavor(models.Model):
    behavor = models.CharField(max_length=40)

    def __str__(self) -> str:
        return f"{self.behavor}"


class Kind(models.Model):
    kind = models.CharField(max_length=100)

    def __str__(self) -> str:
        return f"{self.kind}"


class Cat(models.Model):
    color = models.CharField(Color, max_length=30)
    behavor = models.CharField(Behavor, max_length=30)
    kind = models.CharField(Kind, max_length=30)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f" Color: {self.color}, Behavior: {self.behavor},Kind: {self.kind}"

day20/catsapps/forms.py
from django import forms
from .models import Color, Cat, Behavor, Kind


class KindForm(forms.ModelForm):
    class Meta:
        model = Kind
        fields = ["kind"]
        labels = {"kind": "Gen"}


class BehavorForm(forms.ModelForm):
    class Meta:
        model = Behavor
        fields = ["behavor"]
        labels = {"behavor": "Comportament"}


class ColorForm(forms.ModelForm):
    class Meta:
        model = Color
        fields = ["color"]
        labels = {"Color": "Culoare"}


class CatForm(forms.ModelForm):
    class Meta:
        model = Cat
        fields = ["color", "behavor", "kind"]
        labels = {"color": "Culoare", "behavor": "Comportament", "kind": "Gen"}

day20/catsapps/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Color, Cat, Behavor, Kind
from .forms import CatForm

# Create your views here.
def index(request):
    """Home page of application"""
    return render(request, "catsapps/index.html")


@login_required
def kind(request):
    kind = Kind.objects.all()
    content = {"KIND": kind}
    return render(request, "catsapps/kind.html", content)


def kindbycats(request, kind_id):
    kind = Kind.objects.filter(id=kind_id)
    context = {"KINDBYCATS": kind}
    return render(request, "catsapps/kindbycats.html", context)


def behavor(request):
    behavor = Behavor.objects.all()
    content = {"BEHAVOR": behavor}
    return render(request, "catsapps/behavor.html", content)


def behavorbycats(request, behavor_id):
    behavor = Behavor.objects.filter(id=behavor_id)
    context = {"BEHAVORBYCATS": behavor}
    return render(request, "catsapps/behavorbycats.html", context)


def color(request):
    color = Color.objects.all()
    content = {"COLOR": color}
    return render(request, "catsapps/color.html", content)


def colorbycats(request, color_id):
    color = Color.objects.filter(id=color_id)
    context = {"COLORBYCATS": color}
    return render(request, "catsapps/colorbycats.html", context)


def cats(request):
    cats = Cat.objects.all()
    context = {"CATS": cats}
    return render(request, "catsapps/cats.html", context)


def add_cats(request):

    if request.method != "POST":
        # NO DATE IN REQUEST
        form = CatForm()
    else:
        form = CatForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("catsapps:cats")

    mapper = {"FORM": form}
    return render(request, "catsapps/addCats.html", mapper)


def update_cats(request, cat_id):
    cat = Cat.objects.get(id=cat_id)

    if request.method != "POST":
        # NO DATE IN REQUEST
        form = CatForm(instance=cat)
    else:
        form = CatForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("catsapps:cats")

    mapper = {"FORM": form, "cat": cat}
    return render(request, "catsapps/update_cat.html", mapper)

day20/catsapps/templates/catsapps/addCats.html
{% extends "catsapps/base.html" %}
{% block content %}
<p>Add new cat</p>
<form action="{% url "catsapps:addCats" %}" method="post">
    {% csrf_token %}
    {{ FORM.as_p }}
    <button name="sumbit"> Apend </button>
</form>
{% endblock content %}

day20/catsapps/templates/catsapps/base copy.html
<p><a href="{% url 'catsapps:index' %}">index </a></p>
<p>
    <a href="{% url 'catsapps:kinds' %}">Kind Cat</a>
<p>
    <a href="{% url 'catsapps:behavors' %}">Behavor Cat</a>
<p>
    <a href="{% url 'catsapps:colors' %}">Color Cat</a>
<p>
    <a href="{% url 'catsapps:cats' %}"> Cat</a>
<p>
    <a href="{% url 'catsapps:addCats' %}"> AddCat</a>
<p>
        
{% if user.is_authenticated %}
    Hello, {{user.username}}
   <a href="{% url 'users:logout' %}">Sign Out</a> 
   {% else %}
   <a href="{% url 'users:register' %}">Sign Up</a>
   <a href="{%  url 'users:login' %}">Sign In</a>
{% endif %}   


    
    
{% block content %}{% endblock content %}

day20/catsapps/templates/catsapps/base.html
{% load bootstrap4 %}

<!docstyle html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>Cats</title>
      {% bootstrap_css %}
      {% bootstrap_javascript jquery='full' %}
   </head>

   <body>
      <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
         <a class="navbar-brand" href="{% url 'catsapps:index' %}">Our application</a>
         <button class="navbar-toggler-icon" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation" >
            <span class="navbar-toggler-icon"></span></button>
         <div class="collapse navbar-collapse" id="navbarCollapse">
             <ul class="navbar-nav mr-auto" >
                <a class="nav-link"  href="{% url 'catsapps:cats' %}">Cats</a>
             </ul>
             <ul class="navbar-nav ml-auto">

             <ul class="navbar-nav mr-auto" >
                <a class="nav-link"  href="{% url 'catsapps:addCats' %}">Add Cat</a>
             </ul>
             <ul class="navbar-nav ml-auto">


               {% if user.is_authenticated %}
                  <li class="nav-item">
                     <span class="navbar-text">Hello, {{user.username}}!</span>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'users:logout' %}">Sign Out</a>
                  </li>
               {% else %}
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'users:register' %}">Sign Up</a> 
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{%  url 'users:login' %}">Sign In</a>
                  </li>
               {% endif %}   
            </ul>
         </div>
      </nav>
      <main role="main" class="container">
         <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
         </div>
         <div class="pb-2 mb-2 border-bottom">
            {% block content %}{% endblock content %}
         </div>
      </main>
   </body>
</html>
    

day20/catsapps/templates/catsapps/behavor.html
{% extends "catsapps/base.html" %}
{% load bootstrap4 %}
{% block content %}
    <p>This is overall incomes for all years and depts</p>
     <ul>
        {% for behavor in BEHAVOR %}
            <p><a href="{% url 'catsapps:behavor' behavor.id %}">{{ behavor }}</a></p> 
        {% empty %}
            <li>Call David to fill the list asap!</li>
        {% endfor %}
    </ul>
{% endblock content %}

day20/catsapps/templates/catsapps/behavorbycats.html
{% extends "catsapps/behavor.html" %}
{% load bootstrap4 %}
{% block content %}
  <p>Behavor</p>
  <ul>
    {% for behavorbycats in BEHAVORBYCATS %}
        <p>{{ behavorbycats }} </p>
    {% empty %}
      <li>No Behavor have been added yet.</li>
    {% endfor %}
  </ul>
{% endblock content %}

day20/catsapps/templates/catsapps/cats.html
{% extends "catsapps/base.html" %}
{% load bootstrap4 %}
{% block content %}
  <ul class="list-group">
        {% for cats in CATS %}
            <p>{{ cats }}</p> <a href="{% url 'catsapps:UpdateCat' cats.id %}"> Add </h3>
        {% empty %}
            <li>Call David to fill the list asap!</li>
        {% endfor %}
    </ul>
{% endblock content %}

day20/catsapps/templates/catsapps/catss.html
{% extends "catsapps/cats.html" %}
{% load bootstrap4 %}
{% block content %}
  <p>Cats</p>
  <ul>
    {% for catss in CATSS %}
        <p>{{ catss }} </p>
    {% empty %}
      <li>No cats have been added yet.</li>
    {% endfor %}
  </ul>
{% endblock content %}

day20/catsapps/templates/catsapps/color.html
{% extends "catsapps/base.html" %}
{% load bootstrap4 %}
{% block content %}
    <p>This is overall incomes for all years and depts</p>
     <ul>
        {% for color in COLOR %}
            <p><a href="{% url 'catsapps:color' color.id %}">{{ color }}</a></p>
        {% empty %}
            <li>Call David to fill the list asap!</li>
        {% endfor %}
    </ul>
{% endblock content %}

day20/catsapps/templates/catsapps/colorbycats.html
{% extends "catsapps/color.html" %}
{% load bootstrap4 %}
{% block content %}
  <p>Colors</p>
  <ul>
    {% for colorbycats in COLORBYCATS %}
        <p>{{ colorbycats }} </p>
    {% empty %}
      <li>No color have been added yet.</li>
    {% endfor %}
  </ul>
{% endblock content %}

day20/catsapps/templates/catsapps/index copy.html
{% extends "catsapps/base.html" %}
{% block content %}
    <p>This sate for Cats</p>
{% endblock content %}

day20/catsapps/templates/catsapps/index.html
{% extends "catsapps/base.html" %}
{% block page_header %}
    <div class='jumbotron'>
        <h1 class="display-3">Cats for you</h1>
        <p class="lead">You can add your own cat
        </p>
    </div>  
{% endblock page_header %}

day20/catsapps/templates/catsapps/kind.html
{% extends "catsapps/base.html" %}
{% load bootstrap4 %}
{% block content %}
    <p>This is overall incomes for all years and depts</p>
     <ul>
        {% for kind in KIND %}
            <p><a href="{% url 'catsapps:kind' kind.id %}">{{ kind }}</a></p> 
        {% empty %}
            <li>Call David to fill the list asap!</li>
        {% endfor %}
    </ul>
{% endblock content %}

day20/catsapps/templates/catsapps/kindbycats.html
{% extends "catsapps/kind.html" %}
{% load bootstrap4 %}
{% block content %}
  <p>Kind</p>
  <ul>
    {% for kindbycats in KINDBYCATS %}
        <p>{{ kindbycats }} </p>
    {% empty %}
      <li>No kind have been added yet.</li>
    {% endfor %}
  </ul>
{% endblock content %}

day20/catsapps/templates/catsapps/update_cat.html
{% extends "catsapps/base.html" %}
{% block content %}
<p>update cat</p>

<form action="{% url "catsapps:UpdateCat" cat.id %}" method="post">

    {% csrf_token %}
    {{ FORM.as_p }}
    <button name="sumbit"> Apend </button>
</form>
{% endblock content %}