day39/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns=[
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

day39/orders/urls.py
from django.urls import path 
from . import views

app_name ="orders"

urlpatterns = [
    path("created", views.order_create, name="order_create")
]

day39/shoes/urls.py
from django.urls import path
from . import views

app_name = 'shoes'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
]

day39/store/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
#from django.templatetags.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path("orders/", include('orders.urls', namespace='orders')),
    path("payment/", include('payment.urls', namespace='payment')),
    path('', include('shoes.urls', namespace='shoes')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

day39/cart/models.py
from django.db import models

# Create your models here.

day39/cart/forms.py
from django import forms 
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,21)]
class CartAddProductsForm(forms.Form ):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    def __init__(self, *args, **kwargs):
        if 'pquant' in kwargs.keys():
            pquant = kwargs.pop('pquant')
        else:
            pquant = 1
        super(CartAddProductsForm, self).__init__(*args, **kwargs)
        if pquant >1 and pquant < 21:
            self.fields["quantity"].choices = [
            (i, str(i)) for i in range(1, pquant)]
            
        
    

#[x for x in range(9)]

day39/cart/views.py
import json
from django.shortcuts import render, redirect, get_object_or_404


# Create your views here.

from django.views.decorators.http import require_POST
from shoes.models import Product
from .cart import Cart
from .forms import CartAddProductsForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductsForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,quantity=cd['quantity'], override_quantity=cd['override'])
    #breakpoint()
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:cart_detail")

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart':cart})

day39/cart/templates/cart/detail.html
{% extends "shoes/base.html" %}
{% load static %}

{% block title %}
  Вы заказали
{% endblock %}

{%block content%}
<h1>Ваша корзина</h1>
<table class="cart">
    <thead>
        <tr>
            <th>Фото</th>
            <th>Продукт</th>
            <th>Количество</th>
            <th>Удалить из корзины</th>
            <th>Цена за единицу</th>
            <th>Цена</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href='{{product.get_absolute_url}}'>
                        <img src="{% if product.image %}{{product.image.url}}{%else%}{% static "img/no_image.png"%}{%endif%}">
                    </a>
                </td>
                <td>
                    {{product.name}}
                </td>
                <td>
                    {{item.quantity}}
                </td>
                <td>
                <form action="{% url "cart:cart_remove" product.id %}" method="post">
                  <input type="submit" value="Remove">
                  {% csrf_token %}
                </form>
                </td>
                <td class = "num">
                    NIS {{ item.price }}
                </td>
                <td class = "num">
                     NIS {{ item.total_price }}
                </td>
            </tr>
            {% endwith %}
            {% endfor %}
            <tr class='total'>
                <td>
                    Всего:
                </td>
                <td colspan = 4></td>
                <td class="num"> 
                    NIS {{ cart.get_total_price }}
                </td>
            </tr>
        </tbody>
    </table>
    <p class="text-right" >
        <a href="{% url "shoes:product_list" %}" class = "button light">Продолжить покупки</a>
        <a href="{% url "orders:order_create" %}" class = "button">Создать заказ</a>
    </p>
{%endblock%}