day26/dict/urls.py
from django.urls import path

from . import views

app_name = "dict"

urlpatterns = [
    # HomePage
    path("", views.index, name="index"),
    path("cats", views.cats, name="cats"),
    path("addcat", views.addcat, name="addcat"),
    path("words", views.words, name="words"),
    path("addword", views.addword, name="addword"),
    path("train", views.train, name="train"),
]

day26/lingvo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("dict.urls")),
    path("", include("users.urls")),
]

day26/users/urls.py
from django.urls import path, include
from . import views
app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register')
]

day26/dict/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# Здесь определяем категории для словаря
class Cats(models.Model):
    name = models.CharField(max_length=15, unique=True)
    date_added = models.DateField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.name}"


class Words(models.Model):
    cat = models.ForeignKey(Cats, on_delete=models.CASCADE)
    word = models.CharField(max_length=15, unique=True)
    transc = models.CharField(max_length=40)
    meaning = models.TextField(max_length=200)
    date_added = models.DateField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.word} : {self.meaning}"

day26/dict/forms.py
from django import forms
from .models import Cats, Words


class CatFORM(forms.ModelForm):
    class Meta:
        model = Cats
        fields = ["name"]
        labels = {"name": "Название категории"}


"""  cat = models.ForeignKey(Cats,on_delete=models.CASCADE)
    word = models.CharField(max_length=15, unique=True)
    transc = models.CharField(max_length=40)
    meaning = models.TextField(max_length=200) """


class WordFORM(forms.ModelForm):
    class Meta:
        model = Words
        fields = ["cat", "word", "transc", "meaning"]
        labels = {
            "cat": "",
            "word": "Слово",
            "transc": "Произношение",
            "meaning": "Перевод",
        }

day26/dict/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Cats, Words
from .forms import CatFORM, WordFORM

# Create your views here.


def index(request):
    return render(request, "dict/index.html")


@login_required
def cats(request):
    cats = Cats.objects.filter(author=request.user.id).order_by("name")
    mapper = {"cats": cats}
    return render(request, "dict/cats.html", mapper)


def addcat(request):
    if request.method != "POST":
        form = CatFORM()
    else:
        form = CatFORM(data=request.POST)

        if form.is_valid:
            new_cat = form.save(commit=False)
            new_cat.author = request.user
            new_cat.save()
            return redirect("dict:cats")
    context = {"form": form}
    return render(request, "dict/newcat.html", context)


def words(request):
    words = Words.objects.filter(author=request.user.id).order_by("word")
    mapper = {"words": words}
    return render(request, "dict/words.html", mapper)


def addword(request):
    if request.method != "POST":
        form = WordFORM()
    else:
        form = WordFORM(data=request.POST)

        if form.is_valid:
            new_word = form.save(commit=False)
            new_word.author = request.user
            new_word.save()
            return redirect("dict:words")
    context = {"form": form}
    return render(request, "dict/newword.html", context)


def train(request):
    words = Words.objects.filter(author=request.user.id).order_by("?")[0:3]
    mapper = {"words": words}
    return render(request, "dict/train.html", mapper)

day26/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    if request.method != "POST":
        form = UserCreationForm
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid:
            new_user = form.save()
            login(request, new_user)
            return redirect("dict:index")
    context = {"form": form}
    return render(request, "registration/register.html", context)

day26/dict/templates/dict/base.html
{% load bootstrap4 %}

<!docstyle html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>Dictionary</title>
      {% bootstrap_css %}
      {% bootstrap_javascript jquery='full' %}
   </head>

   <body>
      <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
         <a class="navbar-brand" href="{% url 'dict:index' %}">Our application</a>
         <button class="navbar-toggler-icon" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation" >
            <span class="navbar-toggler-icon"></span></button>
         <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav ml-auto">
               {% if user.is_authenticated %}
                  <li class="nav-item">
                     <span class="navbar-text">Hello, {{user.username}}!</span>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'users:logout' %}">Sign Out</a>
                  </li>
               {% else %}
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'users:register' %}">Sign Up</a> 
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{%  url 'users:login' %}">Sign In</a>
                  </li>
               {% endif %}   
            </ul>
         </div>
      </nav>
      <main role="main" class="container">
         <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
         </div>
         <div class="pb-2 mb-2 border-bottom">
            {% block content %}{% endblock content %}
         </div>
      </main>
   </body>
</html>

day26/dict/templates/dict/cats.html
{% extends "dict/base.html" %}
{% load bootstrap4 %}
{% block page_header %}
  <h2>Список созданых категорий</h2>
  <p>
    <a href="{% url 'dict:addcat'  %}" >Создать новую категорию</a>
  </p>
{% endblock page_header %}
{% block content %}
    <ul class="list-group">
        {% for cat in cats %}
        <li class="list-group-item">{{cat}}</li>
        {% endfor %}
    </ul>
{% endblock content %}

day26/dict/templates/dict/index.html
{% extends "dict/base.html" %}
{% block page_header %}
    <div class='jumbotron'>
        <h1 class="display-3">Dictionaries for you</h1>
        <p class="lead">You can create your own dictionary and use it for learn and fun
        </p>
    </div>  
    {% if user.is_authenticated %}
    <div class="container-fluid">
       <p class="lead">
          <a href="{% url 'dict:cats'  %}" >Словарные категории</a>
       </p>
       <p class="lead">
          <a href="{% url 'dict:words'  %}" >Слова</a>
       </p>
       <p class="lead">
          <a href="{% url 'dict:train'  %}" >Проверь себя</a>
       </p>
    </div>  
    {% endif %}
{% endblock page_header %}

day26/dict/templates/dict/newcat.html
{% extends "dict/base.html" %}
{% load bootstrap4 %}
{% block page_header %}
  <h2>Создаем новую категорию</h2>
{% endblock page_header %}
{% block content %}
    <form method="post" action "{% url 'dict:addcat' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button name="submit" class="btn btn-success">Добавить</button>
        {% endbuttons %}
        <input type="hidden" name="next"
            value="{% url 'dict:cats' %}" />
    </form>
{% endblock content %}

day26/dict/templates/dict/newword.html
{% extends "dict/base.html" %}
{% load bootstrap4 %}
{% block page_header %}
  <h2>Добавляем новое слово</h2>
{% endblock page_header %}
{% block content %}
    <form method="post" action "{% url 'dict:addword' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button name="submit" class="btn btn-success">Добавить</button>
        {% endbuttons %}
        <input type="hidden" name="next"
            value="{% url 'dict:words' %}" />
    </form>
{% endblock content %}

day26/dict/templates/dict/train.html
{% extends "dict/base.html" %}
{% load bootstrap4 %}
{% block page_header %}
  <h2>Проверь себя</h2>
<script> 
function notify(el, id) {
  id.style="color:black"
}
</script>
{% endblock page_header %}
{% block content %}
    <ul class="list-group">
        {% for word in words %}
        <li class="list-group-item" onclick="notify(this, s{{word.id}})">{{word.word}} : <span id=s{{word.id}} class=s{{word.id}} style="color:white;">{{word.transc}} : {{word.meaning}}</span> </li>
        {% endfor %}
    </ul>
{% endblock content %}

day26/dict/templates/dict/words.html
{% extends "dict/base.html" %}
{% load bootstrap4 %}
{% block page_header %}
  <h2>Слова</h2>
  <p>
    <a href="{% url 'dict:addword'  %}" >Добавить слово</a>
  </p>
{% endblock page_header %}
{% block content %}
    <ul class="list-group">
        {% for word in words %}
        <li class="list-group-item">{{word}}</li>
        {% endfor %}
    </ul>
{% endblock content %}